- name: enable the software collections repository (Red Hat)
  rhsm_repository:
    name: rhel-server-rhscl-7-rpms
    state: enabled
  when:
    - ansible_distribution == "RedHat"
    - "'rh-git' in git_package_install.name"

- name: enable the software collections repository (CentOS)
  yum:
    name: centos-release-scl
    state: present
  when:
    - ansible_distribution == "CentOS"
    - "'rh-git' in git_package_install.name"

- name: install new git version
  yum:
    name: "{{ [ git_package_install.name ] + git_package_install.extras }}"

